services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - frontend
      - backend

  postgres_db:
    image: pgvector/pgvector:pg17
    container_name: crm_postgres_container
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: omni_agent

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: crm_backend_container

    restart: always

    expose:
      - "3000"

    env_file:
      - ./backend/.env

    environment:
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      DB_DATABASE: omni_agent

    depends_on:
      - postgres_db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

      args:
        VITE_BACKEND_URL: /api/v1
        VITE_BACKEND_WEBSOCKETS_URL: /api

    container_name: crm_frontend_container

    restart: always

    expose:
      - "80"

    depends_on:
      - backend

volumes:
  pgdata:
