// src/agent/agent.state.ts
import { Annotation } from "@langchain/langgraph";

/**
 * Defining the explicit, type-safe schema that governs our AI Agent workflow.
 * VerbatimModuleSyntax friendly interface structure.
 */
export interface AgentStateInterface {
  ticketId: string;
  customerEmail: string;
  rawIssueText: string;
  
  // Metadata populated dynamically by the Classifier Node
  categories: string[];
  sentiment: "URGENT_CHURN" | "ANGRY" | "NEUTRAL";
  
  // Internal research documentation injected during the RAG database step
  retrievedContextChunks: string[];
  stripeAccountStatus: string | null;
  
  // The operational message outputs generated by the Composer
  draftResponse: string | null;
  criticFeedback: string | null;
  qualityPassed: boolean;
  
  // Human operational override flags
  requiresHumanReview: boolean;
  humanApproved: boolean;
}

/**
 * LangGraph Annotation object. This compiles our TypeScript interface into
 * runtime tracking channels. The reducer functions define how state merges.
 */
export const AgentStateAnnotation = Annotation.Root({
  ticketId: Annotation<string>,
  customerEmail: Annotation<string>,
  rawIssueText: Annotation<string>,
  
  // We use standard assignment reducers (replacing old values with new updates)
  categories: Annotation<string[]>({
    reducer: (x, y) => y ?? x,
    default: () => [],
  }),
  sentiment: Annotation<"URGENT_CHURN" | "ANGRY" | "NEUTRAL">({
    reducer: (x, y) => y ?? x,
    default: () => "NEUTRAL",
  }),
  
  // Reducer accumulates retrieved knowledge base chunks cleanly
  retrievedContextChunks: Annotation<string[]>({
    reducer: (x, y) => x.concat(y ?? []),
    default: () => [],
  }),
  
  stripeAccountStatus: Annotation<string | null>({
    reducer: (x, y) => y ?? x,
    default: () => null,
  }),
  
  draftResponse: Annotation<string | null>({
    reducer: (x, y) => y ?? x,
    default: () => null,
  }),
  criticFeedback: Annotation<string | null>({
    reducer: (x, y) => y ?? x,
    default: () => null,
  }),
  qualityPassed: Annotation<boolean>({
    reducer: (x, y) => y ?? x,
    default: () => false,
  }),
  
  requiresHumanReview: Annotation<boolean>({
    reducer: (x, y) => y ?? x,
    default: () => false,
  }),
  humanApproved: Annotation<boolean>({
    reducer: (x, y) => y ?? x,
    default: () => false,
  }),
});