import { Injectable, OnModuleInit } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { KnowledgeBaseEntity } from './knowledge.entity';
import { GoogleGenAI } from '@google/genai';

@Injectable()
export class KnowledgeService implements OnModuleInit {
  private ai!: GoogleGenAI;

  constructor(
    @InjectRepository(KnowledgeBaseEntity)
    private readonly knowledgeRepo: Repository<KnowledgeBaseEntity>,
  ) {}

  onModuleInit() {
    const apiKey = process.env.GOOGLE_API_KEY;
    if (!apiKey)
      throw new Error(
        'Missing GOOGLE_API_KEY inside your environment configurations.',
      );
    this.ai = new GoogleGenAI({ apiKey });

    // Seed default baseline records if the database is currently empty
    this.seedKnowledgeDatabase();
  }

  /**
   * Helper utility to convert standard text strings into mathematical floating point vector matrices.
   */
  // async generateEmbedding(text: string): Promise<number[]> {
  //   const embeddingModel = this.ai.getEmbeddingModel({
  //     model: 'text-embedding-004',
  //   });
  //   const response = await embeddingModel.embedContent({
  //     content: { parts: [{ text }] },
  //   });
  //   return response.embedding.values;
  // }

  /**
   * Helper utility to convert standard text strings into mathematical floating point vector matrices.
   */
  /**
   * Helper utility to convert standard text strings into mathematical floating point vector matrices.
   */
  /**
   * Helper utility to convert standard text strings into mathematical floating point vector matrices.
   */
  async generateEmbedding(text: string): Promise<number[]> {
    const response = await this.ai.models.embedContent({
      // model: 'text-embedding-004',
      model: 'gemini-embedding-2',
      contents: text,
    });

    if (!response.embeddings?.[0]?.values) {
      throw new Error(
        'Failed to generate embedding: No embedding values returned.',
      );
    }

    return response.embeddings[0].values;
  }

  /**
   * Vector Search Query: Performs raw cosine distance vector similarity lookups against PostgreSQL.
   */
  async findRelevantContext(
    queryText: string,
    categoryFilter: string[],
    limit = 2,
  ): Promise<string[]> {
    try {
      const vector = await this.generateEmbedding(queryText);
      const vectorString = `[${vector.join(',')}]`;

      // Fallback if no matching classification types are generated by the graph
      const categories =
        categoryFilter.length > 0 ? categoryFilter : ['Technical', 'Billing'];

      // Execute a native pgvector operator lookup. <=> calculates cosine distance matrix
      const rawMatches = await this.knowledgeRepo.query(
        `
        SELECT title, content, (embedding::vector <=> $1::vector) as distance
        FROM knowledge_base
        WHERE category = ANY($2)
        ORDER BY distance ASC
        LIMIT $3
        `,
        [vectorString, categories, limit],
      );

      return rawMatches.map(
        (match: any) => `[Doc: ${match.title}] ${match.content}`,
      );
    } catch (error) {
      console.error(
        '[KnowledgeService] Semantic vector search failure:',
        error,
      );
      return [];
    }
  }

  /**
   * Automatically populates baseline technical data on boot to ensure your RAG retrieval executes cleanly.
   */
  private async seedKnowledgeDatabase() {
    const count = await this.knowledgeRepo.count();
    if (count > 0) return;

    console.log(
      '[KnowledgeService] Ingestion running. Seeding baseline semantic vector library entries...',
    );

    const articles = [
      {
        title: 'SSL Sync Timout Fixes',
        category: 'Technical',
        content:
          'Collaborative real-time document sync document engines using web sockets or Yjs/Hocuspocus often run into proxy level blocks. Always update your Nginx configuration block to include: proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection "Upgrade"; proxy_read_timeout 86400s; to completely avoid secure socket termination layers.',
      },
      {
        title: 'Stripe Double Invoicing Adjustments',
        category: 'Billing',
        content:
          'When users encounter duplicate subscription entries or upgrades that fail to synchronize immediately within an active mid-cycle period, open the Stripe dashboard interface, toggle to the customer invoice profile ledger, choose "Credit Note Generation", enter the overcharged value amount, and push update to reset active subscription tier metrics without causing user suspension.',
      },
    ];

    for (const item of articles) {
      const vector = await this.generateEmbedding(item.content);
      const entity = this.knowledgeRepo.create({
        ...item,
        embedding: `[${vector.join(',')}]`,
      });
      await this.knowledgeRepo.save(entity);
    }
    console.log(
      '[KnowledgeService] Ingestion finalized. All baseline embeddings written successfully.',
    );
  }
}
